name: CI

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  unit-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: ./bugtracker-backend/go.sum

      - name: Install go-junit-report
        run: |
          go install github.com/jstemmer/go-junit-reportv2@latest    

      - name: Execute unit tests for backend
        working-directory: ./bugtracker-backend
        run: |
          go test -v ./... 2>&1 | go-junit-report > test-results.xml

      - name: Publish Backend Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Backend Unit Tests
          path: bugtracker-backend/test-results.xml
          reporter: jest-junit

  unit-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./bugtracker-frontend/package-lock.json

      - name: Execute unit tests for frontend
        working-directory: ./bugtracker-frontend
        run: |
          npm install
          npm test

      - name: Publish Frontend Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Frontend Unit Tests
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit