name: CI

on:
  push:
    branches: 
      - main
    workflow dispatch:

    jobs:
      unit-test-backend:
        runs-on: ubuntu-latest
        steps:
          - name: Setup Go environment
            uses: actions/setup-go@v4
            with:
              go-version: '1.21'
              cache-dependency-path: ./bugtracker-backend/go.sum

          - name: Execute unit tests for backend
            uses: actions/checkout@v4
            working-directory: ./bugtracker-backend
            run: |
              go test -v ./...