name: CI

on:
  push:
    branches: 
      - main
    workflow_dispatch:

jobs:
  unit-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: ./bugtracker-backend/go.sum

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute unit tests for backend
        run: |
          go test -v ./...
        working-directory: ./bugtracker-backend
            working-directory: ./bugtracker-backend